services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: krautAndRueben
      POSTGRES_USER: krautAndRueben
      POSTGRES_PASSWORD: krautAndRueben
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U krautAndRueben" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data: