spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/krautAndRueben
    username: krautAndRueben
    password: krautAndRueben

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: krautAndRueben

server:
  port: 8080